name: deploy
on:
  workflow_call:
    inputs:
      test-output:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: report test output
        run: |
          echo "test output: ${{ inputs.test-output }}"
      - name: deploy
        run: echo 'deploying the code'
