name: test-code
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'testing the code'
      - name: inject failure
        run: |
          echo "tests failed" >&2
          exit 1
