name: test-code
on:
  workflow_call:
    outputs:
      testrun:
        value: ${{ jobs.test.outputs.testrun }}
      wat:
        value: ${{ jobs.test.outputs.wat }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'testing the code'
      - name: set output
        id: set-output
        run: |
          echo 'testrun=success' >> "$GITHUB_OUTPUT"
          echo 'other=foo' >> "$GITHUB_OUTPUT"
      - name: check output
        run: |
          echo ${{ steps.set-output.outputs.testrun }}
    outputs:
      testrun: ${{ steps.set-output.outputs.testrun }}
      wat: ${{ toJSON(steps.set-output.outputs.*) }}
