name: test-code
on:
  workflow_call:
    outputs:
      testrun:
        value: ${{ jobs.test.outputs.testrun }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'testing the code'
      - name: inject failure
        run: |
          echo "tests failed" >&2
          exit 1
      - name: set output
        id: set-output
        run: echo 'testrun=success' >> "$GITHUB_OUTPUT"
      - name: check output
        run: |
          echo ${{ steps.set-output.outputs.testrun }}
    outputs:
      testrun: ${{ steps.set-output.outputs.testrun }}
