name: test-code
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'testing the code'
      - name: set output
        id: set-output
        run: echo 'testrun=success' >> "$GITHUB_OUTPUT"
    outputs:
      testrun: ${{ steps.set-output.outputs.testrun }}
